# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

#default:
#  adapter: postgresql
#  encoding: unicode
#  pool: 5

development:
  <<: *default
  database: db/development.sqlite3

#development:
#  adapter: postgresql
#  database: development
#  encoding: unicode
#  pool: 5

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

#production: &prod
#  adapter: postgresql
#  database: <%= ENV['RDS_DB_NAME'] %>
#  host: <%= ENV['RDS_HOSTNAME'] %>
#  password: <%= ENV['RDS_PASSWORD'] %>
#  port: <%= ENV['RDS_PORT'] %>
#  username: <%= ENV['RDS_USERNAME'] %>